### ISSUE TITLE
Outdated instructions for EPEL

### ISSUE THREAD

**Issue by 3xploiton3** [Photon89/shutter-jekyll-site#73]
https://download.fedoraproject.org/pub/epel/7/i386/epel-release-7-8.noarch.rpm

reference:
https://shutter-project.org/downloads/third-party-packages/

![image](https://github.com/shutter-project/shutter/assets/19517680/3b144b12-4854-402c-877c-9263500ff641)

**Comment by Photon89** [comment]
I'll take care of this and other outdated information on the third party packages site!
